/**
 * Syncs release notes from the Quilibrium monorepo (github.com/QuilibriumNetwork/monorepo).
 *
 * 1. Fetches the curated RELEASE-NOTES file from develop branch
 * 2. Discovers version PRs merged to develop
 * 3. For versions missing from RELEASE-NOTES, summarizes merge commits via LLM
 * 4. Outputs combined markdown to docs/custom/auto/Monorepo-Release-Notes.md
 *
 * Usage: tsx scripts/sync-monorepo.ts
 */

import 'dotenv/config';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';

const REPO_OWNER = 'QuilibriumNetwork';
const REPO_NAME = 'monorepo';
const BRANCH = 'develop';
const RELEASE_NOTES_PATH = 'RELEASE-NOTES';
const OUT_PATH = resolve(__dirname, '../docs/custom/auto/Monorepo-Release-Notes.md');
const DEFAULT_MODEL = 'deepseek/deepseek-chat-v3-0324';

// Version PR title pattern: "v2.1.0.XX" or "v2.1.0.XX-pN"
const VERSION_PR_PATTERN = /^v\d+\.\d+\.\d+\.\d+/;

// ── Types ────────────────────────────────────────────────────────────────────

interface VersionNotes {
  version: string;       // e.g. "2.1.0.18"
  shortVersion: string;  // e.g. ".18"
  bullets: string[];     // raw bullet lines
  autoGenerated: boolean;
}

interface VersionPR {
  number: number;
  version: string;
  shortVersion: string;
  mergeCommitSha: string;
  mergedAt: string;
}

// ── GitHub fetch helpers ─────────────────────────────────────────────────────

async function githubFetch(path: string): Promise<Response> {
  const url = `https://api.github.com${path}`;
  const headers: Record<string, string> = {
    Accept: 'application/vnd.github.v3+json',
    'User-Agent': 'quily-chatbot-sync',
  };
  const token = process.env.GITHUB_TOKEN;
  if (token) headers.Authorization = `token ${token}`;

  const res = await fetch(url, { headers });
  if (!res.ok) {
    throw new Error(`GitHub API ${res.status}: ${await res.text().catch(() => '')}`);
  }
  return res;
}

async function fetchRawFile(owner: string, repo: string, branch: string, filePath: string): Promise<string> {
  const url = `https://raw.githubusercontent.com/${owner}/${repo}/${branch}/${filePath}`;
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to fetch ${filePath}: HTTP ${res.status}`);
  }
  return res.text();
}

// ── RELEASE-NOTES parser ─────────────────────────────────────────────────────

function parseReleaseNotes(content: string): VersionNotes[] {
  const versions: VersionNotes[] = [];
  let current: VersionNotes | null = null;

  for (const line of content.split('\n')) {
    const headerMatch = line.match(/^#\s+(\d+\.\d+\.\d+\.\d+)/);
    if (headerMatch) {
      if (current) versions.push(current);
      const version = headerMatch[1];
      const parts = version.split('.');
      current = {
        version,
        shortVersion: `.${parts[parts.length - 1]}`,
        bullets: [],
        autoGenerated: false,
      };
      continue;
    }
    if (current && line.startsWith('- ')) {
      current.bullets.push(line.substring(2).trim());
    }
  }
  if (current) versions.push(current);
  return versions;
}

// ── Version PR discovery ─────────────────────────────────────────────────────

async function fetchVersionPRs(): Promise<VersionPR[]> {
  const res = await githubFetch(
    `/repos/${REPO_OWNER}/${REPO_NAME}/pulls?state=closed&base=${BRANCH}&per_page=30&sort=updated&direction=desc`
  );
  const prs = await res.json() as Array<{
    number: number;
    title: string;
    merged_at: string | null;
    merge_commit_sha: string | null;
  }>;

  const versionPRs: VersionPR[] = [];
  for (const pr of prs) {
    if (!pr.merged_at || !pr.merge_commit_sha) continue;
    const match = pr.title.match(/^v?(\d+\.\d+\.\d+\.\d+)/);
    if (!match) continue;
    const version = match[1];
    const parts = version.split('.');
    versionPRs.push({
      number: pr.number,
      version,
      shortVersion: `.${parts[parts.length - 1]}`,
      mergeCommitSha: pr.merge_commit_sha,
      mergedAt: pr.merged_at,
    });
  }

  // Sort by version number descending (newest first)
  versionPRs.sort((a, b) => {
    const aParts = a.version.split('.').map(Number);
    const bParts = b.version.split('.').map(Number);
    for (let i = 0; i < Math.max(aParts.length, bParts.length); i++) {
      if ((bParts[i] || 0) !== (aParts[i] || 0)) return (bParts[i] || 0) - (aParts[i] || 0);
    }
    return 0;
  });

  return versionPRs;
}

// ── Merge commit helpers ─────────────────────────────────────────────────────

async function fetchMergeCommitMessage(sha: string): Promise<string> {
  const res = await githubFetch(`/repos/${REPO_OWNER}/${REPO_NAME}/commits/${sha}`);
  const data = await res.json() as { commit: { message: string } };
  return data.commit.message;
}

function extractCommitLines(message: string): string[] {
  return message
    .split('\n')
    .map(line => line.trim())
    .filter(line => line.length > 0)
    .filter(line => !line.startsWith('Co-authored-by:'))
    .filter(line => !line.startsWith('---------'))
    .filter(line => !line.match(/^v\d+\.\d+\.\d+\.\d+/))
    .filter(line => !line.match(/^\*\s*v\d+\.\d+\.\d+\.\d+$/))
    .filter(line => line !== '*')
    .map(line => line.replace(/^\*\s*/, ''));
}

function deduplicateCommitLines(
  currentLines: string[],
  previousLines: string[]
): string[] {
  const previousSet = new Set(previousLines.map(l => l.toLowerCase()));
  return currentLines.filter(line => !previousSet.has(line.toLowerCase()));
}

// ── LLM summarization ────────────────────────────────────────────────────────

const SUMMARIZE_SYSTEM_PROMPT = `You are a release notes writer for the Quilibrium node software. You extract user-facing changes from raw commit messages and write concise bullet-point changelogs.

Rules:
- Write each change as a single bullet starting with "- "
- Use lowercase, concise language matching this style:
  - resolve sync race condition with prover registry pruning
  - added DKLs23 fork
  - fixed channel bug
- Ignore: debug logging additions, intermediate fixes, co-author metadata, test scaffolding
- Group related fixes into single bullets when they address the same issue
- Preserve technical terms exactly (e.g. "blossomsub", "hypergraph", "pebble")
- Do NOT invent changes — only summarize what is in the commit messages
- Output ONLY bullet points, no headings or commentary`;

async function summarizeWithLLM(version: string, commitLines: string[]): Promise<string[]> {
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey) throw new Error('OPENROUTER_API_KEY required for gap-filling summarization');

  const model = process.env.MONOREPO_LLM_MODEL || DEFAULT_MODEL;
  const input = commitLines.join('\n');

  const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: 'system', content: SUMMARIZE_SYSTEM_PROMPT },
        {
          role: 'user',
          content: `Here are the raw commit messages from Quilibrium node version ${version}. Write concise release notes:\n\n${input}`,
        },
      ],
      max_tokens: 500,
      temperature: 0.2,
    }),
  });

  if (!response.ok) {
    const body = await response.text().catch(() => '');
    throw new Error(`OpenRouter API error ${response.status}: ${body}`);
  }

  const data = (await response.json()) as {
    choices: { message: { content: string } }[];
  };

  const text = data.choices[0]?.message?.content?.trim() || '';
  return text
    .split('\n')
    .map(line => line.trim())
    .filter(line => line.startsWith('- '))
    .map(line => line.substring(2).trim());
}

function fallbackSummarize(commitLines: string[]): string[] {
  return commitLines
    .filter(line => /^(fix|feat|add|resolve|update|remove)[:(!]/i.test(line))
    .map(line => line.replace(/^(fix|feat):\s*/i, '').trim())
    .filter(line => line.length > 10);
}

// ── Markdown builder ──────────────────────────────────────────────────────────

function buildMarkdown(curated: VersionNotes[], auto: VersionNotes[]): string {
  const all = [...auto, ...curated].sort((a, b) => {
    const aParts = a.version.split('.').map(Number);
    const bParts = b.version.split('.').map(Number);
    for (let i = 0; i < Math.max(aParts.length, bParts.length); i++) {
      if ((bParts[i] || 0) !== (aParts[i] || 0)) return (bParts[i] || 0) - (aParts[i] || 0);
    }
    return 0;
  });

  const dateIso = new Date().toISOString();
  const dateHuman = new Date().toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  });

  let md = `---
title: "Quilibrium Node Release Notes"
source: github.com/QuilibriumNetwork/monorepo (automated daily)
date: ${dateIso.split('T')[0]}
type: release_notes
topics:
  - release notes
  - changelog
  - version
  - update
  - what changed
  - bug fix
  - new feature
  - node update
---

# Quilibrium Node Release Notes

**Last updated:** ${dateHuman}
**Source:** [Quilibrium Monorepo](https://github.com/${REPO_OWNER}/${REPO_NAME})

This document tracks changes in each Quilibrium node release. For the latest release binary, visit [releases.quilibrium.com](https://releases.quilibrium.com/release).

`;

  for (const v of all) {
    const tag = v.autoGenerated ? ' *(auto-generated)*' : '';
    md += `## v${v.version} (version ${v.shortVersion})${tag}\n`;
    for (const bullet of v.bullets) {
      md += `- ${bullet}\n`;
    }
    md += '\n';
  }

  md += `---\n\n*This document is auto-generated daily. Curated notes come from the monorepo RELEASE-NOTES file. Versions marked (auto-generated) are summarized from commit messages and may be less precise.*\n`;

  return md;
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log('Syncing monorepo release notes...');

  // 1. Fetch curated RELEASE-NOTES
  console.log('Fetching RELEASE-NOTES from develop branch...');
  let curatedNotes: VersionNotes[] = [];
  try {
    const content = await fetchRawFile(REPO_OWNER, REPO_NAME, BRANCH, RELEASE_NOTES_PATH);
    curatedNotes = parseReleaseNotes(content);
    console.log(`  Found ${curatedNotes.length} curated versions: ${curatedNotes.map(v => v.version).join(', ')}`);
  } catch (err) {
    console.warn('  Warning: Could not fetch RELEASE-NOTES, will use PR/commit data only');
  }

  // 2. Discover version PRs
  console.log('Fetching version PRs from monorepo...');
  const versionPRs = await fetchVersionPRs();
  console.log(`  Found ${versionPRs.length} version PRs: ${versionPRs.map(v => v.version).join(', ')}`);

  // 3. Identify gaps (versions in PRs but not in RELEASE-NOTES)
  const curatedVersions = new Set(curatedNotes.map(v => v.version));
  const gapPRs = versionPRs.filter(pr => !curatedVersions.has(pr.version));
  console.log(`  Gap versions needing LLM summarization: ${gapPRs.length > 0 ? gapPRs.map(v => v.version).join(', ') : 'none'}`);

  // 4. Fetch merge commit messages for gap versions
  const gapData: Array<{ pr: VersionPR; uniqueLines: string[] }> = [];
  const commitCache = new Map<string, string[]>();

  async function getCommitLines(sha: string): Promise<string[]> {
    if (commitCache.has(sha)) return commitCache.get(sha)!;
    const message = await fetchMergeCommitMessage(sha);
    const lines = extractCommitLines(message);
    commitCache.set(sha, lines);
    return lines;
  }

  for (let i = 0; i < gapPRs.length; i++) {
    const pr = gapPRs[i];
    console.log(`  Fetching merge commit for ${pr.version} (PR #${pr.number})...`);
    const lines = await getCommitLines(pr.mergeCommitSha);

    let previousLines: string[] = [];
    const thisIdx = versionPRs.findIndex(v => v.version === pr.version);
    const prevPR = thisIdx >= 0 ? versionPRs[thisIdx + 1] : undefined;
    if (prevPR) {
      previousLines = await getCommitLines(prevPR.mergeCommitSha);
    }

    const uniqueLines = deduplicateCommitLines(lines, previousLines);
    console.log(`    ${lines.length} total lines → ${uniqueLines.length} unique after dedup`);
    gapData.push({ pr, uniqueLines });
  }

  // 5. Summarize gap versions
  const autoNotes: VersionNotes[] = [];
  const hasApiKey = !!process.env.OPENROUTER_API_KEY;

  for (const { pr, uniqueLines } of gapData) {
    if (uniqueLines.length === 0) {
      console.log(`  Skipping ${pr.version} — no unique commit lines`);
      continue;
    }

    let bullets: string[];
    if (hasApiKey) {
      try {
        console.log(`  Summarizing ${pr.version} via LLM (${uniqueLines.length} lines)...`);
        bullets = await summarizeWithLLM(pr.version, uniqueLines);
        console.log(`    Generated ${bullets.length} bullet points`);
      } catch (err) {
        console.warn(`    LLM failed, using fallback: ${err}`);
        bullets = fallbackSummarize(uniqueLines);
      }
    } else {
      console.log(`  No OPENROUTER_API_KEY — using heuristic fallback for ${pr.version}`);
      bullets = fallbackSummarize(uniqueLines);
    }

    if (bullets.length > 0) {
      autoNotes.push({
        version: pr.version,
        shortVersion: pr.shortVersion,
        bullets,
        autoGenerated: true,
      });
    }
  }

  // 6. Build output document
  const md = buildMarkdown(curatedNotes, autoNotes);

  // Change detection
  if (existsSync(OUT_PATH)) {
    const existing = readFileSync(OUT_PATH, 'utf-8');
    const normalize = (s: string) =>
      s.replace(/^date: .+$/m, '').replace(/^\*\*Last updated:\*\* .+$/m, '');
    if (normalize(existing) === normalize(md)) {
      console.log('No changes detected — release notes are up to date.');
      return;
    }
  }

  writeFileSync(OUT_PATH, md, 'utf-8');
  console.log(`\nWrote release notes to ${OUT_PATH}`);
  console.log(`  Curated versions: ${curatedNotes.length}`);
  console.log(`  Auto-generated versions: ${autoNotes.length}`);
  console.log(`  Total versions: ${curatedNotes.length + autoNotes.length}`);
}

main().catch((err) => {
  // Graceful failure: log warning but exit 0 so CI workflow continues.
  // The existing release notes file (if any) is preserved unchanged.
  console.warn('Warning: monorepo release sync failed, skipping:', err.message || err);
  process.exit(0);
});
