/**
 * Syncs release notes from the Quilibrium monorepo (github.com/QuilibriumNetwork/monorepo).
 *
 * 1. Fetches the curated RELEASE-NOTES file from develop branch
 * 2. Discovers version PRs merged to develop
 * 3. For versions missing from RELEASE-NOTES, summarizes merge commits via LLM
 * 4. Outputs combined markdown to docs/custom/auto/Monorepo-Release-Notes.md
 *
 * Usage: tsx scripts/sync-monorepo.ts
 */

import 'dotenv/config';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';

const REPO_OWNER = 'QuilibriumNetwork';
const REPO_NAME = 'monorepo';
const BRANCH = 'develop';
const RELEASE_NOTES_PATH = 'RELEASE-NOTES';
const OUT_PATH = resolve(__dirname, '../docs/custom/auto/Monorepo-Release-Notes.md');
const DEFAULT_MODEL = 'deepseek/deepseek-chat-v3-0324';

// Version PR title pattern: "v2.1.0.XX" or "v2.1.0.XX-pN"
const VERSION_PR_PATTERN = /^v\d+\.\d+\.\d+\.\d+/;

// ── Types ────────────────────────────────────────────────────────────────────

interface VersionNotes {
  version: string;       // e.g. "2.1.0.18"
  shortVersion: string;  // e.g. ".18"
  bullets: string[];     // raw bullet lines
  autoGenerated: boolean;
}

interface VersionPR {
  number: number;
  version: string;
  shortVersion: string;
  mergeCommitSha: string;
  mergedAt: string;
}

// ── GitHub fetch helpers ─────────────────────────────────────────────────────

async function githubFetch(path: string): Promise<Response> {
  const url = `https://api.github.com${path}`;
  const headers: Record<string, string> = {
    Accept: 'application/vnd.github.v3+json',
    'User-Agent': 'quily-chatbot-sync',
  };
  const token = process.env.GITHUB_TOKEN;
  if (token) headers.Authorization = `token ${token}`;

  const res = await fetch(url, { headers });
  if (!res.ok) {
    throw new Error(`GitHub API ${res.status}: ${await res.text().catch(() => '')}`);
  }
  return res;
}

async function fetchRawFile(owner: string, repo: string, branch: string, filePath: string): Promise<string> {
  const url = `https://raw.githubusercontent.com/${owner}/${repo}/${branch}/${filePath}`;
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to fetch ${filePath}: HTTP ${res.status}`);
  }
  return res.text();
}

// ── RELEASE-NOTES parser ─────────────────────────────────────────────────────

function parseReleaseNotes(content: string): VersionNotes[] {
  const versions: VersionNotes[] = [];
  let current: VersionNotes | null = null;

  for (const line of content.split('\n')) {
    const headerMatch = line.match(/^#\s+(\d+\.\d+\.\d+\.\d+)/);
    if (headerMatch) {
      if (current) versions.push(current);
      const version = headerMatch[1];
      const parts = version.split('.');
      current = {
        version,
        shortVersion: `.${parts[parts.length - 1]}`,
        bullets: [],
        autoGenerated: false,
      };
      continue;
    }
    if (current && line.startsWith('- ')) {
      current.bullets.push(line.substring(2).trim());
    }
  }
  if (current) versions.push(current);
  return versions;
}

// ── Version PR discovery ─────────────────────────────────────────────────────

async function fetchVersionPRs(): Promise<VersionPR[]> {
  const res = await githubFetch(
    `/repos/${REPO_OWNER}/${REPO_NAME}/pulls?state=closed&base=${BRANCH}&per_page=30&sort=updated&direction=desc`
  );
  const prs = await res.json() as Array<{
    number: number;
    title: string;
    merged_at: string | null;
    merge_commit_sha: string | null;
  }>;

  const versionPRs: VersionPR[] = [];
  for (const pr of prs) {
    if (!pr.merged_at || !pr.merge_commit_sha) continue;
    const match = pr.title.match(/^v?(\d+\.\d+\.\d+\.\d+)/);
    if (!match) continue;
    const version = match[1];
    const parts = version.split('.');
    versionPRs.push({
      number: pr.number,
      version,
      shortVersion: `.${parts[parts.length - 1]}`,
      mergeCommitSha: pr.merge_commit_sha,
      mergedAt: pr.merged_at,
    });
  }

  // Sort by version number descending (newest first)
  versionPRs.sort((a, b) => {
    const aParts = a.version.split('.').map(Number);
    const bParts = b.version.split('.').map(Number);
    for (let i = 0; i < Math.max(aParts.length, bParts.length); i++) {
      if ((bParts[i] || 0) !== (aParts[i] || 0)) return (bParts[i] || 0) - (aParts[i] || 0);
    }
    return 0;
  });

  return versionPRs;
}

// ── Merge commit helpers ─────────────────────────────────────────────────────

async function fetchMergeCommitMessage(sha: string): Promise<string> {
  const res = await githubFetch(`/repos/${REPO_OWNER}/${REPO_NAME}/commits/${sha}`);
  const data = await res.json() as { commit: { message: string } };
  return data.commit.message;
}

function extractCommitLines(message: string): string[] {
  return message
    .split('\n')
    .map(line => line.trim())
    .filter(line => line.length > 0)
    .filter(line => !line.startsWith('Co-authored-by:'))
    .filter(line => !line.startsWith('---------'))
    .filter(line => !line.match(/^v\d+\.\d+\.\d+\.\d+/))
    .filter(line => !line.match(/^\*\s*v\d+\.\d+\.\d+\.\d+$/))
    .filter(line => line !== '*')
    .map(line => line.replace(/^\*\s*/, ''));
}

function deduplicateCommitLines(
  currentLines: string[],
  previousLines: string[]
): string[] {
  const previousSet = new Set(previousLines.map(l => l.toLowerCase()));
  return currentLines.filter(line => !previousSet.has(line.toLowerCase()));
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log('Syncing monorepo release notes...');

  // 1. Fetch curated RELEASE-NOTES
  console.log('Fetching RELEASE-NOTES from develop branch...');
  let curatedNotes: VersionNotes[] = [];
  try {
    const content = await fetchRawFile(REPO_OWNER, REPO_NAME, BRANCH, RELEASE_NOTES_PATH);
    curatedNotes = parseReleaseNotes(content);
    console.log(`  Found ${curatedNotes.length} curated versions: ${curatedNotes.map(v => v.version).join(', ')}`);
  } catch (err) {
    console.warn('  Warning: Could not fetch RELEASE-NOTES, will use PR/commit data only');
  }

  // 2. Discover version PRs
  console.log('Fetching version PRs from monorepo...');
  const versionPRs = await fetchVersionPRs();
  console.log(`  Found ${versionPRs.length} version PRs: ${versionPRs.map(v => v.version).join(', ')}`);

  // 3. Identify gaps (versions in PRs but not in RELEASE-NOTES)
  const curatedVersions = new Set(curatedNotes.map(v => v.version));
  const gapPRs = versionPRs.filter(pr => !curatedVersions.has(pr.version));
  console.log(`  Gap versions needing LLM summarization: ${gapPRs.length > 0 ? gapPRs.map(v => v.version).join(', ') : 'none'}`);

  // 4. Fetch merge commit messages for gap versions
  const gapData: Array<{ pr: VersionPR; uniqueLines: string[] }> = [];
  const commitCache = new Map<string, string[]>();

  async function getCommitLines(sha: string): Promise<string[]> {
    if (commitCache.has(sha)) return commitCache.get(sha)!;
    const message = await fetchMergeCommitMessage(sha);
    const lines = extractCommitLines(message);
    commitCache.set(sha, lines);
    return lines;
  }

  for (let i = 0; i < gapPRs.length; i++) {
    const pr = gapPRs[i];
    console.log(`  Fetching merge commit for ${pr.version} (PR #${pr.number})...`);
    const lines = await getCommitLines(pr.mergeCommitSha);

    let previousLines: string[] = [];
    const thisIdx = versionPRs.findIndex(v => v.version === pr.version);
    const prevPR = thisIdx >= 0 ? versionPRs[thisIdx + 1] : undefined;
    if (prevPR) {
      previousLines = await getCommitLines(prevPR.mergeCommitSha);
    }

    const uniqueLines = deduplicateCommitLines(lines, previousLines);
    console.log(`    ${lines.length} total lines → ${uniqueLines.length} unique after dedup`);
    gapData.push({ pr, uniqueLines });
  }

  console.log('Done.');
}

main().catch((err) => {
  // Graceful failure: log warning but exit 0 so CI workflow continues.
  // The existing release notes file (if any) is preserved unchanged.
  console.warn('Warning: monorepo release sync failed, skipping:', err.message || err);
  process.exit(0);
});
